version: '3.6'

services:    
  sqlServer:
    container_name: sqlServer
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    image: mcr.microsoft.com/mssql/server
    volumes:
      - ../Volumes/sqlServer:/app
